# Generated by Django 5.2.7 on 2025-11-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion_parada', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('visibilidad_pagina', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField(help_text='Duración del recorrido en minutos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('paradas', models.ManyToManyField(related_name='recorridos', to='recorrido.parada')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_itinerario', models.DateField()),
                ('hora_itinerario', models.TimeField()),
                ('cupos', models.IntegerField()),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='recorrido.recorrido')),
            ],
        ),
    ]
