# Generated by Django 5.2.7 on 2025-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='duracion',
            field=models.IntegerField(help_text='MIN'),
        ),
    ]
