# Generated by Django 5.2.7 on 2025-11-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0002_alter_parada_estado_alter_recorrido_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='imagen',
            field=models.ImageField(blank=True, default='/static/img/paradas/default.jpg', null=True, upload_to='paradas/'),
        ),
    ]
