# Generated by Django 5.2.7 on 2025-11-08 22:27

import apps.recorrido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0003_parada_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorrido',
            old_name='descripcion',
            new_name='descripcion_recorrido',
        ),
        migrations.AddField(
            model_name='recorrido',
            name='nombre_recorrido',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parada',
            name='imagen',
            field=models.ImageField(blank=True, default='paradas/default.jpg', null=True, upload_to=apps.recorrido.models.renombrar_imagen_parada),
        ),
    ]
