# Generated by Django 5.2.7 on 2025-11-14 04:12

import apps.recorrido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0004_rename_descripcion_recorrido_descripcion_recorrido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.recorrido.models.renombrar_imagen_parada),
        ),
    ]
