# Generated by Django 5.2.7 on 2025-11-08 23:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorrido', '0004_rename_descripcion_recorrido_descripcion_recorrido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la notificación')),
                ('es_publica', models.BooleanField(default=True, help_text='Si es True, se muestra en la página principal para todos')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('itinerario_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='recorrido.itinerario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asientos', models.PositiveSmallIntegerField(help_text='Cantidad de asientos que reserva el turista', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la reserva')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('A', 'Cancelada')], default='P', help_text='Estado actual de la reserva (Pendiente, Confirmada, Cancelada)', max_length=1)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='recorrido.itinerario')),
                ('punto_partida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_origen', to='recorrido.parada')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
